services:
  db:
    image: postgres:14-alpine
    restart: always
    container_name: db-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbpassy
      POSTGRES_DB: travel_contest_db
    ports:
      - '5431:5432'
  api:
    build: .
    ports:
      - 5000:8080
    environment:
      DB_PORT: 5431
      DB_USER: postgres
      DB_HOST: localhost
      DB_DATABASE: travel_contest_db
      DB_PASSWORD: dbpassy
      PORT: 5000
  depends_on:
    - db
  command: sh -c "sleep 10 && docker exec db-container"
