services:
  db:
    container_name: db-container
    build:
      context: ./database
      dockerfile: Dockerfile
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'

  api:
    container_name: api-container
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 5001:8080
